backend:
  name: git-gateway
  repo: interactwith/docs
  branch: main

media_folder: static/cmsi
public_folder: /cmsi

collections:
  - label: "Single Pages"
    name: "pages"
    files:
      - label: "Introduction Page"
        name: "introduction"
        file: "docs/whitepaper/0-intro.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}

  - name: 'whitepaper-sections'
    label: 'Whitepaper Sections'
    folder: 'docs/whitepaper'
    path: '{{slug}}/_category_'
    create: true
    slug: '{{customProps.customSlug}}'
    extension: yml
    identifier_field: label
    fields:
      - { label: 'Title', name: 'label', widget: 'string' }
      - label: 'Custom props'
        name: 'customProps' 
        widget: 'object'
        fields:
          - { label: 'Slug', name: 'customSlug', widget: 'string' }

      # - { label: 'Tab', name: 'tab', widget: 'relation', collection: 'blogTabs', search_fields: ['title'], value_field: 'title', display_fields: ['title'] }
      # - { label: "Post type", name: "post_type", widget: "select", options: [ 'updates', 'events', 'tutorials']}
      # - { label: 'Description', name: 'description', widget: 'text' }
      # - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'whitepaper-pages'
    label: 'Whitepaper Pages'
    folder: 'docs/whitepaper'
    path: '{{section}}/{{slug}}'
    format: 'frontmatter'
    summary: '{{section}} - {{title}}'
    create: true
    slug: '{{sidebar_position}}-{{slug}}'
    filter: { field: "is_dynamic", value: true }
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Position', name: 'sidebar_position', widget: 'number' }
      - { label: 'Dynamic', name: 'is_dynamic', widget: 'hidden', default: true }
      - { label: 'Section', name: 'section', widget: 'relation', collection: 'whitepaper-sections', search_fields: ['label'], value_field: 'customProps.customSlug', display_fields: ['label'] }
      - { label: 'Body', name: 'body', widget: 'markdown' }